=== carstenbock/sipp_ipsec/sipp.dtd
<!ELEMENT scenario ( init | CallLengthRepartition | ResponseTimeRepartition | Global | User | Reference | DefaultMessage | send | recv | pause | nop | sendCmd | recvCmd | label | timewait | xi:include)* >
<!ATTLIST scenario
  name CDATA #IMPLIED
  xmlns:xi CDATA #IMPLIED
>

<!-- Replaced by the file href names: the children of its <scenario>, or
     else its root element. A relative href is relative to the file that
     includes it. -->
<!ELEMENT xi:include EMPTY >
<!ATTLIST xi:include href CDATA #REQUIRED >

<!ELEMENT init ( nop | label )* >

<!-- The parameters of a pause's or a sample's distribution. -->
<!ENTITY % distributionParams '
  value CDATA #IMPLIED
  min CDATA #IMPLIED
  max CDATA #IMPLIED
  mean CDATA #IMPLIED
  stdev CDATA #IMPLIED
  lambda CDATA #IMPLIED
  k CDATA #IMPLIED
  x_m CDATA #IMPLIED
  shape CDATA #IMPLIED
  scale CDATA #IMPLIED
  location CDATA #IMPLIED
  theta CDATA #IMPLIED
  n CDATA #IMPLIED
  p CDATA #IMPLIED
  '>

<!-- BEGIN message commands -->

<!ENTITY % messageCmdCommon '
  start_rtd CDATA #IMPLIED
  rtd CDATA #IMPLIED
  repeat_rtd (true|false) #IMPLIED
  crlf (true|false) #IMPLIED
  next NMTOKEN #IMPLIED
  test NMTOKEN #IMPLIED
  chance NMTOKEN #IMPLIED
  condexec NMTOKEN #IMPLIED
  condexec_inverse NMTOKEN #IMPLIED
  counter NMTOKEN #IMPLIED
  hide (true|false) #IMPLIED
  hiderest (true|false) #IMPLIED
  '>

<!ELEMENT send (#PCDATA|action)* >
<!ATTLIST send %messageCmdCommon; >
<!ATTLIST send retrans NMTOKEN #IMPLIED >
<!ATTLIST send lost NMTOKEN #IMPLIED >
<!ATTLIST send start_txn NMTOKEN #IMPLIED >
<!ATTLIST send ack_txn NMTOKEN #IMPLIED >
<!ATTLIST send response_txn NMTOKEN #IMPLIED >
<!ATTLIST send dialog NMTOKEN #IMPLIED >
<!ATTLIST send timeout NMTOKEN #IMPLIED >
<!ATTLIST send ontimeout NMTOKEN #IMPLIED >

<!ELEMENT recv ( action? ) >
<!ATTLIST recv %messageCmdCommon; >
<!ATTLIST recv response CDATA #IMPLIED >
<!ATTLIST recv request CDATA #IMPLIED >
<!ATTLIST recv optional (true|global|false) #IMPLIED >
<!ATTLIST recv advance_state (true|false) #IMPLIED >
<!ATTLIST recv ignoresdp (true|false) #IMPLIED >
<!ATTLIST recv rrs (true|false) #IMPLIED >
<!ATTLIST recv auth (true|false) #IMPLIED >
<!ATTLIST recv lost NMTOKEN #IMPLIED >
<!ATTLIST recv timeout CDATA #IMPLIED >
<!ATTLIST recv ontimeout NMTOKEN #IMPLIED >
<!ATTLIST recv regexp_match (true|false) #IMPLIED >
<!ATTLIST recv response_txn NMTOKEN #IMPLIED >
<!ATTLIST recv start_txn NMTOKEN #IMPLIED >
<!ATTLIST recv dialog NMTOKEN #IMPLIED >

<!ELEMENT pause EMPTY >
<!ATTLIST pause %messageCmdCommon; >
<!ATTLIST pause milliseconds NMTOKEN #IMPLIED >
<!ATTLIST pause variable NMTOKEN #IMPLIED >
<!ATTLIST pause distribution NMTOKEN #IMPLIED >
<!ATTLIST pause %distributionParams; >
<!ATTLIST pause sanity_check (true|false) #IMPLIED >

<!ELEMENT nop ( action? ) >
<!ATTLIST nop %messageCmdCommon; >
<!ATTLIST nop display CDATA #IMPLIED >
<!ATTLIST nop ontimeout NMTOKEN #IMPLIED >

<!ELEMENT sendCmd ( #PCDATA ) >
<!ATTLIST sendCmd %messageCmdCommon; >
<!ATTLIST sendCmd dest NMTOKEN #IMPLIED >

<!ELEMENT recvCmd ( action? ) >
<!ATTLIST recvCmd %messageCmdCommon; >
<!ATTLIST recvCmd src NMTOKEN #IMPLIED >
<!ATTLIST recvCmd optional (true|global|false) #IMPLIED >

<!-- END message commands -->

<!ELEMENT label ( #PCDATA ) >
<!ATTLIST label id NMTOKEN #IMPLIED >

<!ELEMENT ResponseTimeRepartition EMPTY >
<!ATTLIST ResponseTimeRepartition value CDATA #REQUIRED >

<!ELEMENT CallLengthRepartition EMPTY >
<!ATTLIST CallLengthRepartition value CDATA #REQUIRED >

<!ELEMENT action ( add | assign | assignstr | closecon | divide | ereg | error | exec | gettimeofday | index | insert | ipsec_setup | ipsec_teardown | jump | log | lookup | multiply | pauserestore | replace | rtp_dtmf | rtp_echo | rtp_stats | sample | setdest | s6a_auth | s6a_purge | s6a_update_location | s6a_wait_cancel | s8_create_session | s8_delete_session | s8_wait_bearer | strcmp | subtract | swu_attach | swu_detach | test | todouble | trim | urldecode | urlencode | verifyauth | warning )+ >

<!-- BEGIN actions -->

<!-- the right-hand side of an arithmetic action: one of value or variable -->
<!ENTITY % rhs '
  value CDATA #IMPLIED
  variable CDATA #IMPLIED
  '>

<!-- string and numeric comparisons: assign_to may be left out when
     check_it or check_it_inverse is set; one of value or variable2 -->
<!ENTITY % comparison '
  assign_to CDATA #IMPLIED
  variable CDATA #REQUIRED
  value CDATA #IMPLIED
  variable2 CDATA #IMPLIED
  check_it (true|false) #IMPLIED
  check_it_inverse (true|false) #IMPLIED
  '>

<!ELEMENT ereg EMPTY >
<!ATTLIST ereg assign_to CDATA #REQUIRED >
<!ATTLIST ereg check_it (true|false) "false" >
<!ATTLIST ereg check_it_inverse (true|false) #IMPLIED >
<!ATTLIST ereg case_indep (true|false) #IMPLIED >
<!ATTLIST ereg header CDATA #IMPLIED >
<!ATTLIST ereg occurrence CDATA #IMPLIED >
<!-- old misspelling of occurrence -->
<!ATTLIST ereg occurence CDATA #IMPLIED >
<!ATTLIST ereg regexp CDATA #REQUIRED >
<!ATTLIST ereg search_in (msg|body|hdr|var) "msg" >
<!ATTLIST ereg start_line (true|false) #IMPLIED >
<!-- the variable to search when search_in="var" -->
<!ATTLIST ereg variable CDATA #IMPLIED >

<!ELEMENT log EMPTY >
<!ATTLIST log message CDATA #REQUIRED >

<!ELEMENT warning EMPTY >
<!ATTLIST warning message CDATA #REQUIRED >

<!ELEMENT error EMPTY >
<!ATTLIST error message CDATA #REQUIRED >

<!ELEMENT exec EMPTY >
<!-- exactly one of these must be present -->
<!ATTLIST exec command CDATA #IMPLIED >
<!ATTLIST exec lua CDATA #IMPLIED >
<!ATTLIST exec verify CDATA #IMPLIED >
<!ATTLIST exec int_cmd (stop_now|stop_gracefully|stop_call) "stop_call" >
<!ATTLIST exec play_pcap_audio CDATA #IMPLIED >
<!ATTLIST exec play_pcap_image CDATA #IMPLIED >
<!ATTLIST exec play_pcap_video CDATA #IMPLIED >
<!ATTLIST exec play_pcap_text CDATA #IMPLIED >
<!ATTLIST exec play_dtmf CDATA #IMPLIED >
<!ATTLIST exec rtp_stream CDATA #IMPLIED >
<!-- with rtp_stream="wait" -->
<!ATTLIST exec timeout NMTOKEN #IMPLIED >
<!ATTLIST exec rtp_echo CDATA #IMPLIED >

<!ELEMENT rtp_echo EMPTY >
<!ATTLIST rtp_echo %rhs; >

<!ELEMENT rtp_stats EMPTY >
<!ATTLIST rtp_stats assign_to CDATA #REQUIRED >
<!ATTLIST rtp_stats media (audio|video) "audio" >

<!ELEMENT rtp_dtmf EMPTY >
<!ATTLIST rtp_dtmf assign_to CDATA #REQUIRED >
<!ATTLIST rtp_dtmf payload_type CDATA "96" >

<!ELEMENT strcmp EMPTY >
<!ATTLIST strcmp %comparison; >

<!ELEMENT test EMPTY >
<!ATTLIST test %comparison; >
<!ATTLIST test compare (equal|not_equal|greater_than|less_than|greater_than_equal|less_than_equal) #REQUIRED >

<!ELEMENT assign EMPTY >
<!ATTLIST assign assign_to CDATA #REQUIRED %rhs; >

<!ELEMENT add EMPTY >
<!ATTLIST add assign_to CDATA #REQUIRED %rhs; >

<!ELEMENT subtract EMPTY >
<!ATTLIST subtract assign_to CDATA #REQUIRED %rhs; >

<!ELEMENT multiply EMPTY >
<!ATTLIST multiply assign_to CDATA #REQUIRED %rhs; >

<!ELEMENT divide EMPTY >
<!ATTLIST divide assign_to CDATA #REQUIRED %rhs; >

<!ELEMENT jump EMPTY >
<!ATTLIST jump %rhs; >

<!ELEMENT pauserestore EMPTY >
<!ATTLIST pauserestore %rhs; >

<!ELEMENT assignstr EMPTY >
<!ATTLIST assignstr assign_to CDATA #REQUIRED >
<!ATTLIST assignstr value CDATA #REQUIRED >

<!ELEMENT todouble EMPTY >
<!ATTLIST todouble assign_to CDATA #REQUIRED >
<!ATTLIST todouble variable CDATA #REQUIRED >

<!ELEMENT sample EMPTY >
<!ATTLIST sample assign_to CDATA #REQUIRED >
<!ATTLIST sample distribution (fixed|uniform|normal|lognormal|exponential|weibull|pareto|gpareto|gamma|negbin) #REQUIRED >
<!ATTLIST sample %distributionParams; >

<!ELEMENT gettimeofday EMPTY >
<!-- two comma-separated variables: seconds,microseconds -->
<!ATTLIST gettimeofday assign_to CDATA #REQUIRED >

<!ELEMENT index EMPTY >
<!ATTLIST index assign_to CDATA #REQUIRED >

<!ELEMENT trim EMPTY >
<!ATTLIST trim assign_to CDATA #REQUIRED >

<!ELEMENT urldecode EMPTY >
<!ATTLIST urldecode variable CDATA #REQUIRED >

<!ELEMENT urlencode EMPTY >
<!ATTLIST urlencode variable CDATA #REQUIRED >

<!ELEMENT verifyauth EMPTY >
<!ATTLIST verifyauth assign_to CDATA #REQUIRED >
<!ATTLIST verifyauth username CDATA #REQUIRED >
<!ATTLIST verifyauth password CDATA #REQUIRED >

<!ELEMENT lookup EMPTY >
<!ATTLIST lookup assign_to CDATA #REQUIRED >
<!ATTLIST lookup file CDATA #REQUIRED >
<!ATTLIST lookup key CDATA #REQUIRED >

<!ELEMENT insert EMPTY >
<!ATTLIST insert file CDATA #REQUIRED >
<!ATTLIST insert value CDATA #REQUIRED >

<!ELEMENT replace EMPTY >
<!ATTLIST replace file CDATA #REQUIRED >
<!ATTLIST replace line CDATA #REQUIRED >
<!ATTLIST replace value CDATA #REQUIRED >

<!ELEMENT setdest EMPTY >
<!ATTLIST setdest host CDATA #REQUIRED >
<!ATTLIST setdest port CDATA #REQUIRED >
<!ATTLIST setdest protocol CDATA #REQUIRED >

<!ELEMENT closecon EMPTY >

<!ELEMENT ipsec_setup EMPTY >
<!ELEMENT ipsec_teardown EMPTY >

<!ELEMENT swu_attach EMPTY >
<!ATTLIST swu_attach identity CDATA #REQUIRED >
<!ATTLIST swu_attach k CDATA #REQUIRED >
<!ATTLIST swu_attach opc CDATA #REQUIRED >
<!ATTLIST swu_attach apn CDATA "ims" >
<!ATTLIST swu_attach pdn_type CDATA "ipv4" >
<!ATTLIST swu_attach sip_family CDATA #IMPLIED >
<!ELEMENT swu_detach EMPTY >

<!ELEMENT s8_create_session EMPTY >
<!ATTLIST s8_create_session imsi CDATA #REQUIRED >
<!ATTLIST s8_create_session msisdn CDATA #IMPLIED >
<!ATTLIST s8_create_session mei CDATA #IMPLIED >
<!ATTLIST s8_create_session apn CDATA "ims" >
<!ATTLIST s8_create_session plmn CDATA #IMPLIED >
<!ATTLIST s8_create_session qci CDATA "5" >
<!ATTLIST s8_create_session arp CDATA "9" >
<!ATTLIST s8_create_session ambr_ul CDATA #IMPLIED >
<!ATTLIST s8_create_session ambr_dl CDATA #IMPLIED >
<!ATTLIST s8_create_session tac CDATA "1" >
<!ATTLIST s8_create_session eci CDATA "1" >
<!ATTLIST s8_create_session pdn_type CDATA "ipv4" >
<!ATTLIST s8_create_session sip_family CDATA #IMPLIED >
<!ATTLIST s8_create_session expect CDATA "16" >
<!ATTLIST s8_create_session assign_to CDATA #IMPLIED >
<!ELEMENT s8_delete_session EMPTY >
<!ATTLIST s8_delete_session expect CDATA "16" >
<!ATTLIST s8_delete_session assign_to CDATA #IMPLIED >
<!ELEMENT s6a_auth EMPTY >
<!ATTLIST s6a_auth imsi CDATA #IMPLIED >
<!ATTLIST s6a_auth expect CDATA "2001" >
<!ATTLIST s6a_auth assign_to CDATA #IMPLIED >
<!ELEMENT s6a_update_location EMPTY >
<!ATTLIST s6a_update_location imsi CDATA #IMPLIED >
<!ATTLIST s6a_update_location apn CDATA "ims" >
<!ATTLIST s6a_update_location mei CDATA #IMPLIED >
<!ATTLIST s6a_update_location expect CDATA "2001" >
<!ATTLIST s6a_update_location assign_to CDATA #IMPLIED >
<!ELEMENT s6a_purge EMPTY >
<!ATTLIST s6a_purge expect CDATA "2001" >
<!ATTLIST s6a_purge assign_to CDATA #IMPLIED >
<!ELEMENT s6a_wait_cancel EMPTY >
<!ATTLIST s6a_wait_cancel timeout CDATA "5000" >
<!ATTLIST s6a_wait_cancel optional (true|false) "false" >
<!ATTLIST s6a_wait_cancel assign_to CDATA #IMPLIED >
<!ELEMENT s8_wait_bearer EMPTY >
<!ATTLIST s8_wait_bearer qci CDATA #IMPLIED >
<!ATTLIST s8_wait_bearer released (true|false) "false" >
<!ATTLIST s8_wait_bearer timeout CDATA "5000" >
<!ATTLIST s8_wait_bearer optional (true|false) "false" >
<!ATTLIST s8_wait_bearer assign_to CDATA #IMPLIED >

<!-- END actions -->

<!-- a pause that ends the scenario, without next or ontimeout -->
<!ELEMENT timewait EMPTY >
<!ATTLIST timewait %messageCmdCommon; >
<!ATTLIST timewait milliseconds NMTOKEN #IMPLIED >
<!ATTLIST timewait variable NMTOKEN #IMPLIED >
<!ATTLIST timewait distribution NMTOKEN #IMPLIED >
<!ATTLIST timewait %distributionParams; >
<!ATTLIST timewait sanity_check (true|false) #IMPLIED >

<!ELEMENT Global EMPTY >
<!ATTLIST Global variables CDATA #REQUIRED >

<!ELEMENT User EMPTY >
<!ATTLIST User variables CDATA #REQUIRED >

<!ELEMENT Reference EMPTY >
<!ATTLIST Reference variables CDATA #REQUIRED >

<!-- replaces one of SIPp's built-in messages, such as the BYE of an
     aborted call -->
<!ELEMENT DefaultMessage ( #PCDATA ) >
<!ATTLIST DefaultMessage id (3pcc_abort|ack|ack2|bye|cancel|200) #REQUIRED >

=== carstenbock/sipp_ipsec/regress/github-#0488/uas.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">
<!-- Challenges with SHA-384, which SIPp doesn't support, first and MD5
     second, and accepts an answer to the MD5 one. [qop] is the MD5
     one's qop parameter. -->
<scenario name="two challenges uas">
  <recv request="REGISTER"/>
  <send>
    <![CDATA[
      SIP/2.0 401 Unauthorized
      [last_Via:]
      [last_From:]
      [last_To:];tag=srv
      [last_Call-ID:]
      [last_CSeq:]
      WWW-Authenticate: Digest realm="r", nonce="n1", algorithm=SHA-384, qop="auth"
      WWW-Authenticate: Digest realm="r", [qop], nonce="n2", algorithm=MD5
      Content-Length: 0
    ]]>
  </send>
  <recv request="REGISTER">
    <action>
      <ereg regexp="nonce=&quot;n2&quot;" search_in="hdr" header="Authorization:" check_it="true" assign_to="_"/>
      <verifyauth assign_to="authvalid" username="alice" password="secret"/>
    </action>
  </recv>
  <nop test="authvalid" next="good"/>
  <send next="end">
    <![CDATA[
      SIP/2.0 403 Forbidden
      [last_Via:]
      [last_From:]
      [last_To:];tag=srv
      [last_Call-ID:]
      [last_CSeq:]
      Content-Length: 0
    ]]>
  </send>
  <label id="good"/>
  <send>
    <![CDATA[
      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:];tag=srv
      [last_Call-ID:]
      [last_CSeq:]
      Content-Length: 0
    ]]>
  </send>
  <label id="end"/>
</scenario>

=== carstenbock/sipp_ipsec/sipp_scenarios/s6a_roaming_not_allowed.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<!--
  S8 home-routed roaming: the home HSS refuses a roaming UE (3GPP TS 29.272
  clauses 5.2.3.1.3 and 5.2.1.1.3, DIAMETER_ERROR_ROAMING_NOT_ALLOWED)

  SIPp is the visited network's MME. Each call is one UE that must NOT get
  service in the visited PLMN given with -visited_plmn:
    1. Authentication-Information-Request. An HSS may refuse here already.
    2. Otherwise Update-Location-Request, which has to be refused.
  The call passes when the HSS answers 5004 to one of them, and fails on
  success or on any other result. No PDN connection is opened and nothing
  is sent to the PGW or the P-CSCF.

  Usage:
    ./sipp -sf s6a_roaming_not_allowed.xml \
      -s6a_peer <dra_or_hss> -s6a_dest_realm epc.mnc<MNC>.mcc<MCC>.3gppnetwork.org \
      -visited_plmn 00101 -t un -inf barred.csv <any address>

  barred.csv, one UE per line:  <imsi>
  The same scenario with another PLMN in -visited_plmn shows that the
  refusal depends on the visited network. S6a alone needs no privileges.
-->

<scenario name="S8HR roaming not allowed">

  <nop>
    <action>
      <s6a_auth imsi="[field0]" expect="any" assign_to="air"/>
    </action>
  </nop>
  <nop>
    <action>
      <test assign_to="refused_at_air" variable="air" compare="equal" value="5004"/>
    </action>
  </nop>
  <nop next="refused" test="refused_at_air"/>

  <!-- Authenticated: the refusal has to come with the location update.
       expect="5004" fails the call on anything else, success included. -->
  <nop>
    <action>
      <s6a_update_location expect="5004"/>
    </action>
  </nop>

  <label id="refused"/>
  <nop>
    <action>
      <log message="S6a [field0]: roaming not allowed (AIR [$air], last result [s6a_result])"/>
    </action>
  </nop>

</scenario>
